CREATE DATABASE INDITEX;
GO
USE INDITEX;
GO
CREATE SCHEMA SGABOXTYPE;
GO
USE INDITEX;
GO

CREATE TABLE SGABOXTYPE.BOX_TYPE (
    BOX_TYPE_ID INT NOT NULL IDENTITY(1,1),
    NAME NVARCHAR(50) NOT NULL,
    HEIGHT INT NOT NULL,
    WIDTH INT NOT NULL,
    DEPTH INT NOT NULL,
    EMPTY_WEIGHT INT NOT NULL,
    CREATED_DATE DATETIME2(3) NOT NULL,
    CREATED_USER NVARCHAR(40) NOT NULL,
    UPDATED_DATE DATETIME2(3),
    UPDATED_USER NVARCHAR(40),
    DEACTIVATED_DATE DATETIME2(3),
    DEACTIVATED_USER NVARCHAR(40),
    CONSTRAINT PK_BOX_TYPE PRIMARY KEY (BOX_TYPE_ID)
);
GO

USE INDITEX;

INSERT INTO SGABOXTYPE.BOX_TYPE 
(NAME, HEIGHT, WIDTH, DEPTH, EMPTY_WEIGHT, CREATED_DATE, CREATED_USER)
 VALUES 
    ('S', 10, 10, 10, 1, GETDATE(), 'LEGO'), 
    ('M', 20, 20, 20, 1.5, GETDATE(), 'LEGO'), 
    ('L', 30, 30, 30, 2, GETDATE(), 'LEGO'), 
    ('XL', 40, 40, 40, 4, GETDATE(), 'LEGO');
GO
