name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: openmarket-356106
  GAR_LOCATION: europe
  SERVICE: sql-db
  REGION: europe-southwest1
  REPOSITORY: rep-sql-db
  

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      #- name: Create Repository
      #  run: |-
      #   gcloud artifacts repositories create ${{ env.REPOSITORY }} --repository-format=docker --location=${{ env.REGION }} --description="Repositorio SQL" 


      # gcloud auth configure-docker --quiet
      - name: Docker Auth        
        run: |-      
         gcloud auth configure-docker --quiet
         gcloud auth configure-docker europe-southwest1-docker.pkg.dev --quiet 
         gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet         
         gcloud auth configure-docker eu.gcr.io-docker.pkg.dev --quiet
         

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      # END - Docker auth and build

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
